# Offense count: 18
# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 54

# Offense count: 5
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 75

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 14
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 42

# Offense count: 2
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 1
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 8

# Offense count: 5
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db, os, pp
Naming/MethodParameterName:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, conditionals
Style/AndOr:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/tokens_controller.rb'
    - 'db/seeds.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ProceduralMethods, FunctionalMethods, IgnoredMethods, AllowBracesOnProceduralOneLiners, BracesRequiredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining, always_braces
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'app/controllers/sentences_controller.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'config/initializers/attack.rb'
    - 'db/seeds.rb'
    - 'test/test_helper.rb'

# Offense count: 29
Style/Documentation:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/bundle'
    - 'bin/setup'
    - 'bin/update'
    - 'test/test_helper.rb'

# Offense count: 50
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/tokens_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: line_count_dependent, lambda, literal
Style/Lambda:
  Exclude:
    - 'app/controllers/sources_controller.rb'

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

# Offense count: 19
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'app/controllers/robots_txts_controller.rb'
    - 'db/alignment_precompute.rb'
    - 'db/seeds.rb'
    - 'lib/translate_tags.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Exclude:
    - 'db/alignment_precompute.rb'

# Offense count: 19
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle, IgnoredMethods.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/application_controller.rb'

# Offense count: 6
# Cop supports --auto-correct.
Style/ParallelAssignment:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/controllers/robots_txts_controller.rb'
    - 'app/controllers/tokens_controller.rb'
    - 'config/spring.rb'
    - 'db/alignment_precompute.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantPercentQ:
  Exclude:
    - 'app/controllers/robots_txts_controller.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 338
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/robots_txts_controller.rb'
    - 'config/application.rb'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'config/routes.rb'
    - 'db/schema.rb'
    - 'lib/translate_tags.rb'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 8

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'db/alignment_precompute.rb'
    - 'db/seeds.rb'

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'app/controllers/dictionaries_controller.rb'
    - 'app/controllers/lemmas_controller.rb'
    - 'app/controllers/sentences_controller.rb'
    - 'app/controllers/sources_controller.rb'
    - 'app/controllers/tokens_controller.rb'
    - 'config/initializers/attack.rb'
    - 'db/seeds.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 4

# Offense count: 17
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 651
